name: Pana

on:
  pull_request:
  workflow_dispatch:

jobs:
  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed lib
      - run: dart pub global activate pana
      - run: pana --no-warning --exit-code-threshold 160
